name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Installer Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Étape 3 : Construire l’image Docker
      - name: Build Docker image
        run: docker build -t projetdocker .

      # Étape 4 : Lancer les tests unitaires
      - name: Run unit tests
        run: |
          pip install -r requirements.txt
          pytest tests/

      # Étape 5 : Se connecter à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Étape 6 : Pousser l’image sur Docker Hub
      - name: Push image
        run: |
          docker tag projetdocker ${{ secrets.DOCKER_USERNAME }}/projetdocker:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/projetdocker:latest
